### ISSUE TITLE
JsonError: data did not match any variant of untagged enum RxPk

### ISSUE THREAD

**Issue by nosmaster89** [helium/gateway-rs#440] opened 2023-08-02 18:44 UTC
gwrs recieved this packet data and returned this error
```ignoring semtech udp parsing error invalid Json string for PushData frame: {
   "rxpk":[
      {
         "jver":1,
         "tmst":1305359278,
         "tm32":3116791260,
         "chan":0,
         "rfch":1,
         "freq":868.100000,
         "mid":8,
         "stat":-1,
         "modu":"LORA",
         "datr":"SF5BW125",
         "codr":"4/7",
         "rssis":-100,
         "lsnr":-6.8,
         "foff":19378,
         "rssi":-93,
         "size":254,
         "data":"UuPpZap3fgVsOdPy6YXPN+Edsvc6V2lA6TYGWmSHPx/tF5+aHvw2zIUxR8BYO0WgmpHdxs8B1PRYGpEh/c0Hvpt4eWTRn92VJ/debff5EgUoWaogaZmmU1i5fER0cfL0cfpW8nevUIH+IQez2NqRtY13Fo8s3oj3KN+iJWLUP2xi+o0M8kcaqDZcbiKjkBxas87gxwAjrBZ/EF+LP8sheuNXUXcUZi1l2f4ocSRtpZS9LHsSoUkXPm6/bz1LoiZfem7smFGm7czFWi/LRbzDVTNSe7yJprdF0Z0biko8Y/e8Na1GHBeu3S9Mzx8xjCX8MGO9z2lFvwMpU3wq+2A="
      }
   ]
} JsonError: data did not match any variant of untagged enum RxPk at line 1 column 566```

**Comment by lthiery** [comment] 2023-08-02 19:38
This was caused by the new spreading factor and appears to be resolved by this PR

https://github.com/helium/semtech-udp/pull/82

**Comment by madninja** [comment] 2023-08-03 03:51
Pick up in https://github.com/helium/gateway-rs/pull/437

**Closed by madninja** 2023-08-03 03:51 UTC
