### ISSUE TITLE
Problem  processing helium traffic

### ISSUE THREAD

**Issue by disk91** [helium/gateway-rs#107] opened 2021-09-24 20:53 UTC
On a gateway I was not able to receive Helium traffic, even if the gateway is receiving LoRaWan communication regularly. I did have to restart the gateway_rs service to restore the helium communications.
In the Logs during that period, I noticed:
```
Sep 24 19:05:42 ubuntu-Standard-PC-i440FX-PIIX-1996 helium_gateway[139580]: uplink @3065586964 us, 867.30 MHz, Ok(DataRate(SF9, BW125)), snr: -10.8, len: 23 from MacAddress(
AC:1F:09:FF:FE:05:89), module: gateway
Sep 24 19:05:42 ubuntu-Standard-PC-i440FX-PIIX-1996 helium_gateway[139580]: ignoring router dispatch error, module: dispatcher
Sep 24 19:05:42 ubuntu-Standard-PC-i440FX-PIIX-1996 helium_gateway[139580]: uplink @3065791964 us, 868.10 MHz, Ok(DataRate(SF11, BW125)), snr: -10, len: 23 from MacAddress(A
C:1F:09:FF:FE:05:89), module: gateway
Sep 24 19:06:12 ubuntu-Standard-PC-i440FX-PIIX-1996 helium_gateway[139580]: no update found, module: updater
Sep 24 19:06:29 ubuntu-Standard-PC-i440FX-PIIX-1996 helium_gateway[139580]: uplink @3111993428 us, 867.30 MHz, Ok(DataRate(SF12, BW125)), snr: -14.5, len: 24 from MacAddress
(AC:1F:09:FF:FE:05:89), module: gateway
Sep 24 19:06:31 ubuntu-Standard-PC-i440FX-PIIX-1996 helium_gateway[139580]: uplink @3114229356 us, 867.10 MHz, Ok(DataRate(SF12, BW125)), snr: -6, len: 18 from MacAddress(AC
:1F:09:FF:FE:05:89), module: gateway
Sep 24 19:06:47 ubuntu-Standard-PC-i440FX-PIIX-1996 helium_gateway[139580]: uplink @3129986196 us, 867.50 MHz, Ok(DataRate(SF9, BW125)), snr: -9.3, len: 23 from MacAddress(A
C:1F:09:FF:FE:05:89), module: gateway
Sep 24 19:06:47 ubuntu-Standard-PC-i440FX-PIIX-1996 helium_gateway[139580]: ignoring router dispatch error, module: dispatcher
Sep 24 19:07:04 ubuntu-Standard-PC-i440FX-PIIX-1996 helium_gateway[139580]: uplink @3147841700 us, 867.30 MHz, Ok(DataRate(SF9, BW125)), snr: -8.3, len: 23 from MacAddress(A
C:1F:09:FF:FE:05:89), module: gateway
Sep 24 19:07:04 ubuntu-Standard-PC-i440FX-PIIX-1996 helium_gateway[139580]: ignoring router dispatch error, module: dispatcher
Sep 24 19:07:07 ubuntu-Standard-PC-i440FX-PIIX-1996 helium_gateway[139580]: uplink @3150565228 us, 867.10 MHz, Ok(DataRate(SF9, BW125)), snr: -6.3, len: 23 from MacAddress(A
C:1F:09:FF:FE:05:89), module: gateway
Sep 24 19:07:07 ubuntu-Standard-PC-i440FX-PIIX-1996 helium_gateway[139580]: ignoring router dispatch error, module: dispatcher
Sep 24 19:07:12 ubuntu-Standard-PC-i440FX-PIIX-1996 helium_gateway[139580]: uplink @3155733180 us, 867.10 MHz, Ok(DataRate(SF12, BW125)), snr: -3.8, len: 18 from MacAddress(
AC:1F:09:FF:FE:05:89), module: gateway
Sep 24 19:07:22 ubuntu-Standard-PC-i440FX-PIIX-1996 helium_gateway[139580]: uplink @3165747444 us, 867.50 MHz, Ok(DataRate(SF9, BW125)), snr: 3.3, len: 25 from MacAddress(AC
:1F:09:FF:FE:05:89), module: gateway

```
After restarting, the **ignoring router dispatch error,** has disappeared from the logs.
In the overall traffic, the frames with that message are corresponding to helium traffic.

**Comment by madninja** [comment] 2021-09-24 22:00
Duplicate of #103

**Closed** 2021-09-24 22:01 UTC
